#!/usr/bin/env python3

from src.agent import Agent

import argparse
import sys

# ------------------------------------------------------------------
# Main Function
# ------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Start Secure TCP Client")
    parser.add_argument('--config', default='/opt/mon-agent/data/config/agent.conf', help='Path to config file (default: agent.conf)')
    parser.add_argument('--host', help='Server IP to connect to')
    parser.add_argument('--port', type=int, help='Server port to connect to')
    parser.add_argument('--cafile', help='Path to server CA certificate file')
    parser.add_argument('--logfile', help='Path to log file')
    args = parser.parse_args()

    agent = Agent(args.config)
    agent.set_server_args(args.host, args.port, args.cafile)
    if args.logfile:
        agent.set_logger(args.logfile)
    try:
        agent.start()
    except KeyboardInterrupt:
        agent.stop()
        sys.exit(0)

if __name__ == "__main__":
    main()